# Generated by Django 2.2.4 on 2019-10-05 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='College',
            new_name='Student',
        ),
    ]
